red_hanger/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = []

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns


urlpatterns += [
    # path("account/", include("red_hanger.user.urls", namespace="user")),
    # path("account/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    path("", include("red_hanger.home.urls")),
]

red_hanger/home/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from .views import current_time, error

urlpatterns = [
    path(r"current-time/", current_time, name="current_time"),
    path(r"error/", error, name="error"),
    path(r"", TemplateView.as_view(template_name="index.html"), name="home"),
]

red_hanger/user/urls.py
from django.urls import path

from .views import login, signup, user_redirect_view, welcome

app_name = "user"
urlpatterns = [
    path("login/", view=login, name="account_login"),
    path("signup/", view=signup, name="account_signup"),
    path("welcome/", view=welcome, name="account_welcome"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
]

red_hanger/home/models.py
# from django.db import models  # NOQA

# from django_extensions.db.models import AutoSlugField  # NOQA
# from model_utils.models import TimeStampedModel  # NOQA

# Create your models here.

red_hanger/user/models.py
from django.contrib import auth
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils.models import TimeStampedModel


class UserManager(BaseUserManager):
    use_in_migrations = True

    @classmethod
    def normalize_email(cls, email):
        """All email providers treat emails in a case-insensitive manner."""
        email = email or ""
        return email.lower()

    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            is_active=True,
            **extra_fields,
        )
        user.password = make_password(password)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)

    def get_by_natural_key(self, username):  # Used by contrib.auth.backends.ModelBackend
        return self.get(email__iexact=username)

    def with_perm(  # noqa
        self,
        perm,
        is_active=True,
        include_superusers=True,
        backend=None,
        obj=None,
    ):
        if backend is None:
            backends = auth._get_backends(return_tuples=True)  # noqa
            if len(backends) == 1:
                backend, _ = backends[0]
            else:
                raise ValueError(
                    "You have multiple authentication backends configured and "
                    "therefore must provide the `backend` argument."
                )
        elif not isinstance(backend, str):
            raise TypeError(f"backend must be a dotted import path string (got {backend}).")
        else:
            backend = auth.load_backend(backend)
        if hasattr(backend, "with_perm"):
            return backend.with_perm(
                perm,
                is_active=is_active,
                include_superusers=include_superusers,
                obj=obj,
            )
        return self.none()


class User(TimeStampedModel, AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        _("email address"),
        unique=True,
        error_messages={"unique": _("A user with that email address already exists.")},
    )
    first_name = models.CharField(_("first name"), max_length=30, blank=True)
    last_name = models.CharField(_("last name"), max_length=30, blank=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as "
            "active. Unselect this instead of deleting accounts."
        ),
    )

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """Returns the first_name plus the last_name, with a space in between."""
        full_name = f"{self.first_name} {self.last_name}"
        return full_name.strip()

    def get_short_name(self):
        """Returns the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Sends an email to this User."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self):
        name = self.get_full_name()
        return name if name else self.email

    def get_absolute_url(self):
        """
        The absolute url of the user model
        """
        raise NotImplementedError()

red_hanger/util/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from .util import file_url


class TestFileModel(models.Model):
    file_field = models.ImageField(_("foo"), upload_to=file_url("filez"))

    class Meta:
        verbose_name = _("test")
        verbose_name_plural = _("tests")

    def __str__(self):
        return f"Test Model: {self.file_field}"

red_hanger/user/forms.py
from allauth.account.forms import (
    LoginForm as AllAuthLoginForm,
    SignupForm as AllAuthSignupForm,
)
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import User


class HasAccountForm(forms.Form):
    email = forms.EmailField(help_text=_("We won't spam you"), required=True)

    def clean_email(self):
        data = self.cleaned_data["email"]
        return data.lower()


class LoginForm(AllAuthLoginForm):
    template_name = "account/login_form.html"
    remember = forms.BooleanField(
        help_text=_("For 2 weeks"),
        label=_("Remember Me"),
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["login"].widget = forms.HiddenInput()


class SignupForm(AllAuthSignupForm):
    template_name = "account/signup_form.html"

    first_name = forms.CharField(
        label=_("First Name"),
        min_length=1,
        max_length=User._meta.get_field("first_name").max_length,
        widget=forms.TextInput(
            attrs={"placeholder": _("First Name"), "autocomplete": "given-name"}
        ),
    )

    last_name = forms.CharField(
        label=_("Last Name"),
        min_length=1,
        max_length=User._meta.get_field("last_name").max_length,
        widget=forms.TextInput(
            attrs={"placeholder": _("Last Name"), "autocomplete": "family-name"}
        ),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].widget.attrs["readonly"] = True
        self.fields["email"].label = "Email"
        self.fields["email2"].label = "Confirm Email"
        self.fields["password2"].label = "Confirm Password"

red_hanger/home/views.py
# Create your views here.

from django.contrib import messages
from django.template.response import TemplateResponse


def error(request):
    """Generate an exception. Useful for e.g. configuring Sentry"""
    raise Exception("Make response code 500!")


def current_time(request):
    """Generate the current time. Useful for testing htmx"""
    messages.info(request, "updated the current time")
    return TemplateResponse(request, "current_time.html")

red_hanger/user/views.py
from allauth.account.views import (
    LoginView as AllAuthLoginView,
    SignupView as AllAuthSignupView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.response import TemplateResponse
from django.views.generic import RedirectView
from django_htmx.http import HttpResponseClientRedirect

from .forms import HasAccountForm
from .models import User


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get(self, request, *args, **kwargs):
        url = self.get_redirect_url(*args, **kwargs)
        if request.htmx:
            return HttpResponseClientRedirect(url)
        return super().get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return "/"


user_redirect_view = UserRedirectView.as_view()


class SignupView(AllAuthSignupView):
    def get_initial(self):
        """Return the initial data to use for forms on this view."""
        email = self.request.GET.get("email", "")
        data = self.initial.copy()
        data["email"] = email
        return data


signup = SignupView.as_view()


class LoginView(AllAuthLoginView):
    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        if hasattr(self.request, "prefetched_user"):
            user = self.request.prefetched_user
        else:
            user = User.objects.get(email__iexact=self.get_form().data["login"])
        ctx["user"] = user
        return ctx

    def get_initial(self):
        """Return the initial data to use for forms on this view."""
        email = self.request.GET.get("email", "")
        data = self.initial.copy()
        data["login"] = email
        return data


login = LoginView.as_view()


def welcome(request):
    if not request.htmx or "email" not in request.GET:
        return TemplateResponse(request, "account/welcome.html", {"form": HasAccountForm()})

    form = HasAccountForm(request.GET)
    if not form.is_valid():
        return TemplateResponse(request, "account/welcome.html", {"form": form})

    try:
        email = form.cleaned_data.get("email")
        request.prefetched_user = User.objects.get(email=email)
        return login(request)
    except User.DoesNotExist:
        return signup(request)

red_hanger/templates/header/base.html
<header x-data="{open: false}" class="fixed top-0 left-0 right-0 z-40">
  <nav class="bg-[#ff0000] border-b-8 border-red-700">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-center h-16">
        <div class="flex">
          {% comment %} {% include "header/mobile_menu_button.html" %} {% endcomment %}
          <h1 class="font-mono m-auto text-xl sm:text-3xl text-white font-extrabold">Women's rights are human rights</h1>
          {% comment %} {% include "header/desktop_center.html" %} {% endcomment %}
        </div>
        {% comment %} <div class="flex items-center">{% include "header/end.html" %}</div> {% endcomment %}
      </div>
    </div>
    {% include "header/mobile_menu.html" %}
  </nav>
</header>

red_hanger/templates/header/desktop_center.html
<div class="hidden md:ml-6 md:flex md:space-x-8">
    <!-- Current: "border-indigo-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
    <a href="#"
       class="border-indigo-500 text-gray-900 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium"> Dashboard </a>
    <a href="#"
       class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium"> Team </a>
    <a href="#"
       class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium"> Projects </a>
    <a href="#"
       class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium"> Calendar </a>
</div>

red_hanger/templates/header/end.html
{% if not request.user.is_authenticated %}
    <div class="flex-shrink-0">
        <a href="{% url "user:account_welcome" %}"
           class="inline-block bg-white py-2 px-4 border border-transparent rounded-md text-base font-medium text-grey-600 hover:bg-grey-50">
            Sign in
        </a>
    </div>
{% else %}
    <div class="hidden md:ml-4 md:flex-shrink-0 md:flex md:items-center">
        <!-- Profile dropdown -->
        {% component_block "flyout" menu_style="origin-top-right absolute right-0 mt-2 w-48  py-1 bg-white focus:outline-none" button_style="bg-white rounded-full flex text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %}
        {% slot button %}
        <span class="sr-only">Open user menu</span>
        <svg class="h-8 w-8 rounded-full"
             xmlns="http://www.w3.org/2000/svg"
             fill="none"
             viewBox="0 0 24 24"
             stroke="currentColor"
             strokeWidth
             2>
            <path strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/>
        </svg>
    {% endslot button %}
    {% slot "content" %}
    <div class=""
         role="menu"
         aria-orientation="vertical"
         aria-labelledby="user-menu-button"
         tabindex="-1">
        <!-- Active: "bg-gray-100", Not Active: "" -->
        <a href="#"
           class="block px-4 py-2 text-sm text-gray-700"
           role="menuitem"
           tabindex="-1"
           id="user-menu-item-0">Your Profile</a>
        <a href="#"
           class="block px-4 py-2 text-sm text-gray-700"
           role="menuitem"
           tabindex="-1"
           id="user-menu-item-1">Settings</a>
        <a href="{% url "account_logout" %}"
           class="block px-4 py-2 text-sm text-gray-700"
           role="menuitem"
           tabindex="-1">
            Sign out
        </a>
    </div>
{% endslot %}
{% endcomponent_block %}
</div>
{% endif %}

red_hanger/templates/header/logo.html
<div class="flex-shrink-0 flex items-center">
  <a href="{% url "home" %}">
    <img class="block lg:hidden h-8 w-auto"
         src="{% static 'img/wire_hanger.svg' %}"
         alt=""/>
    <img class="hidden lg:block h-8 w-auto"
         src="{% static 'img/wire_hanger.svg' %}"
         alt=""/>
  </a>
</div>

red_hanger/templates/header/mobile_menu.html
<div class="fixed bg-white w-full md:hidden"
     id="mobile-menu"
     x-cloak
     x-show="open"
     x-transition:enter="transition ease-out duration-200"
     x-transition:enter-start="opacity-0 -translate-x-1"
     x-transition:enter-end="opacity-100 translate-x-0"
     x-transition:leave="transition ease-in duration-150"
     x-transition:leave-start="opacity-100 translate-x-0"
     x-transition:leave-end="opacity-0 -translate-x-1"
     style="display: none;">
    <div class="pt-2 pb-3 space-y-1">
        <!-- Current: "bg-indigo-50 border-indigo-500 text-indigo-700", Default: "border-transparent text-gray-500 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-700" -->
        <a href="#"
           class="bg-indigo-50 border-indigo-500 text-indigo-700 block pl-3 pr-4 py-2 border-l-4 text-base font-medium sm:pl-5 sm:pr-6">Dashboard</a>
        <a href="#"
           class="border-transparent text-gray-500 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-700 block pl-3 pr-4 py-2 border-l-4 text-base font-medium sm:pl-5 sm:pr-6">Team</a>
        <a href="#"
           class="border-transparent text-gray-500 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-700 block pl-3 pr-4 py-2 border-l-4 text-base font-medium sm:pl-5 sm:pr-6">Projects</a>
        <a href="#"
           class="border-transparent text-gray-500 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-700 block pl-3 pr-4 py-2 border-l-4 text-base font-medium sm:pl-5 sm:pr-6">Calendar</a>
    </div>
    <div class="pt-4 pb-3 border-t border-gray-200">
        <div class="flex items-center px-4 sm:px-6">
            <div class="flex-shrink-0">
                <img class="h-10 w-10 rounded-full"
                     src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                     alt="">
            </div>
            <div class="ml-3">
                <div class="text-base font-medium text-gray-800">Tom Cook</div>
                <div class="text-sm font-medium text-gray-500">tom@example.com</div>
            </div>
            <button type="button"
                    class="ml-auto flex-shrink-0 bg-white p-1 rounded-full text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                <span class="sr-only">View notifications</span>
            </button>
        </div>
        <div class="mt-3 space-y-1">
            <a href="#"
               class="block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100 sm:px-6">Your Profile</a>
            <a href="#"
               class="block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100 sm:px-6">Settings</a>
            <a href="#"
               class="block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100 sm:px-6">Sign out</a>
        </div>
    </div>
</div>

red_hanger/templates/header/mobile_menu_button.html
<div class="-ml-2 mr-2 flex items-center md:hidden">
    <!-- Mobile menu button -->
    <button type="button"
            class="inline-flex items-center justify-center p-4 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500"
            aria-controls="mobile-menu"
            @click="open=!open"
            :aria-expanded="open">
        <span class="sr-only">Open main menu</span>
        <div class="w-6 flex items-center justify-center relative">
            <span x-bind:class="open ? 'translate-y-0 rotate-45' : '-translate-y-2'"
                  class="transform transition w-full h-px bg-current absolute"></span>
            <span x-bind:class="open ? 'opacity-0 translate-x-3' : 'opacity-100'"
                  class="transform transition w-full h-px bg-current absolute"></span>
            <span x-bind:class="open ? 'translate-y-0 -rotate-45' : 'translate-y-2'"
                  class="transform transition w-full h-px bg-current absolute"></span>
        </div>
    </button>
</div>